# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/item.proto

require 'google/protobuf'

require 'core/item_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.UserId" do
    optional :value, :int64, 1
  end
  add_message "protocol.Item" do
    optional :item_category, :enum, 1, "protocol.core.ItemCategory"
    optional :item_id, :int32, 2
    optional :count, :int32, 3
  end
  add_message "protocol.UserCrystal" do
    optional :free_count, :int32, 1
    optional :paid_count, :int32, 2
  end
  add_message "protocol.UserCard" do
    optional :id, :string, 1
    optional :user_id, :message, 2, "protocol.UserId"
    optional :card_id, :int32, 3
    optional :exp, :int32, 4
    optional :level, :int32, 5
  end
  add_message "protocol.UserInventory" do
    repeated :items, :message, 1, "protocol.Item"
    repeated :user_cards, :message, 2, "protocol.UserCard"
    optional :user_crystal, :message, 3, "protocol.UserCrystal"
  end
end

module Protocol
  UserId = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.UserId").msgclass
  Item = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.Item").msgclass
  UserCrystal = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.UserCrystal").msgclass
  UserCard = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.UserCard").msgclass
  UserInventory = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.UserInventory").msgclass
end
