# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/login.proto

require 'google/protobuf'

require 'rpc/metadata_pb'
require 'rpc/item_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.rpc.UserId" do
    optional :value, :int64, 1
  end
  add_message "protocol.rpc.CreateUserRequest" do
    optional :device_id, :string, 1
    optional :name, :string, 2
  end
  add_message "protocol.rpc.CreateUserResponse" do
    optional :metadata, :message, 1, "protocol.rpc.Metadata"
  end
  add_message "protocol.rpc.CreateSessionRequest" do
    optional :device_id, :string, 1
  end
  add_message "protocol.rpc.CreateSessionResponse" do
    optional :metadata, :message, 1, "protocol.rpc.Metadata"
    optional :session_token, :string, 2
  end
  add_message "protocol.rpc.LoginRequest" do
    optional :session_token, :string, 1
  end
  add_message "protocol.rpc.LoginResponse" do
    optional :metadata, :message, 1, "protocol.rpc.Metadata"
    optional :user_id, :message, 2, "protocol.rpc.UserId"
    optional :user_inventory, :message, 3, "protocol.UserInventory"
  end
end

module Protocol
  module Rpc
    UserId = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.UserId").msgclass
    CreateUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.CreateUserRequest").msgclass
    CreateUserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.CreateUserResponse").msgclass
    CreateSessionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.CreateSessionRequest").msgclass
    CreateSessionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.CreateSessionResponse").msgclass
    LoginRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.LoginRequest").msgclass
    LoginResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.LoginResponse").msgclass
  end
end
