# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/metadata.proto

require 'google/protobuf'

require 'rpc/error_details_pb'
require 'rpc/code_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.rpc.Metadata" do
    optional :status_code, :enum, 1, "protocol.rpc.StatusCode"
    repeated :error_details, :message, 2, "protocol.rpc.ErrorDetail"
  end
end

module Protocol
  module Rpc
    Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.rpc.Metadata").msgclass
  end
end
