# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/item.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "protocol.core.ItemCategory" do
    value :ITEM_CATEGORY_CRYSTAL, 0
    value :ITEM_CATEGORY_COIN, 1
    value :ITEM_CATEGORY_STAMINA, 2
    value :ITEM_CATEGORY_USER_EXP, 3
    value :ITEM_CATEGORY_CARD, 4
  end
end

module Protocol
  module Core
    ItemCategory = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.core.ItemCategory").enummodule
  end
end
