# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.spanner_example.Metadata" do
    optional :status_code, :enum, 1, "protocol.spanner_example.StatusCode"
  end
  add_enum "protocol.spanner_example.StatusCode" do
    value :OK, 0
    value :UNKNOWN, 1
    value :INVALID_ARGUMENT, 2
  end
end

module Protocol
  module SpannerExample
    Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.Metadata").msgclass
    StatusCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.StatusCode").enummodule
  end
end
