# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_enum "protocol.StatusCode" do
    value :OK, 0
    value :UNKNOWN, 1
    value :INVALID_ARGUMENT, 2
  end
end

module Protocol
  StatusCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.StatusCode").enummodule
end
