# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.UserId" do
    optional :value, :int64, 1
  end
end

module Protocol
  UserId = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.UserId").msgclass
end
