# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

require 'google/protobuf'

require 'code_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.spanner_example.UserId" do
    optional :value, :int64, 1
  end
  add_message "protocol.spanner_example.CreateUserRequest" do
    optional :device_id, :string, 1
    optional :name, :string, 2
  end
  add_message "protocol.spanner_example.CreateUserResponse" do
    optional :metadata, :message, 1, "protocol.spanner_example.Metadata"
  end
  add_message "protocol.spanner_example.CreateSessionRequest" do
    optional :device_id, :string, 1
  end
  add_message "protocol.spanner_example.CreateSessionResponse" do
    optional :metadata, :message, 1, "protocol.spanner_example.Metadata"
    optional :session_token, :string, 2
  end
  add_message "protocol.spanner_example.LoginRequest" do
    optional :session_token, :string, 1
  end
  add_message "protocol.spanner_example.LoginResponse" do
    optional :metadata, :message, 1, "protocol.spanner_example.Metadata"
    optional :user_id, :message, 2, "protocol.spanner_example.UserId"
  end
end

module Protocol
  module SpannerExample
    UserId = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.UserId").msgclass
    CreateUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.CreateUserRequest").msgclass
    CreateUserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.CreateUserResponse").msgclass
    CreateSessionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.CreateSessionRequest").msgclass
    CreateSessionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.CreateSessionResponse").msgclass
    LoginRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.LoginRequest").msgclass
    LoginResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.spanner_example.LoginResponse").msgclass
  end
end
