# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

require 'google/protobuf'

require 'core_pb'
require 'metadata_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.CreateUserRequest" do
    optional :device_id, :string, 1
    optional :name, :string, 2
  end
  add_message "protocol.CreateUserResponse" do
    optional :metadata, :message, 1, "protocol.Metadata"
  end
  add_message "protocol.CreateSessionRequest" do
    optional :device_id, :string, 1
  end
  add_message "protocol.CreateSessionResponse" do
    optional :metadata, :message, 1, "protocol.Metadata"
    optional :session_token, :string, 2
  end
  add_message "protocol.LoginRequest" do
    optional :session_token, :string, 1
  end
  add_message "protocol.LoginResponse" do
    optional :metadata, :message, 1, "protocol.Metadata"
    optional :user_id, :message, 2, "protocol.UserId"
  end
end

module Protocol
  CreateUserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.CreateUserRequest").msgclass
  CreateUserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.CreateUserResponse").msgclass
  CreateSessionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.CreateSessionRequest").msgclass
  CreateSessionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.CreateSessionResponse").msgclass
  LoginRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.LoginRequest").msgclass
  LoginResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.LoginResponse").msgclass
end
