# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadata.proto

require 'google/protobuf'

require 'error_details_pb'
require 'code_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protocol.Metadata" do
    optional :status_code, :enum, 1, "protocol.StatusCode"
    repeated :error_details, :message, 2, "protocol.ErrorDetail"
  end
end

module Protocol
  Metadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol.Metadata").msgclass
end
